service: mercury

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  region: eu-west-1

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn'

functions:
  parser:
    handler: src/mercury-parser.default
    description: Mercury parser
    timeout: 10
    memorySize: 512
    events:
      - http:
          method: get
          path: /
          cors: true
      - schedule:
          rate: rate(15 minutes)
          enabled: true

plugins:
  - serverless-webpack
  - serverless-offline
